<?php
/**
 * RosmonSMS — Production Installer
 * ==================================
 * Visit: https://yourdomain.com/install.php
 *
 * BEFORE RUNNING:
 *   1. Edit config/env.php with your supervisor DB credentials
 *   2. Create the supervisor DB in cPanel (e.g. middlehi_IDAHOSA)
 *   3. Create all 50 tenant DBs in cPanel:
 *      middlehi_IDAHOSA_1 through middlehi_IDAHOSA_50
 *      (each with matching user + password = DB name)
 *   4. Visit this page and follow the steps
 *   5. DELETE this file after successful installation!
 */

define('ROOT_PATH', __DIR__);
session_start();

// ── Security: lock after install ──────────────────────────────────────
if (file_exists(__DIR__ . '/.installed')) {
    die("
    <div style='font-family:sans-serif;max-width:600px;margin:80px auto;text-align:center;'>
      <h2 style='color:#16a34a;'>&#10003; RosmonSMS is already installed.</h2>
      <p>Delete <code>.installed</code> from the server root to re-run the installer.</p>
      <a href='/' style='display:inline-block;margin-top:20px;padding:12px 28px;background:#2563eb;color:#fff;border-radius:8px;text-decoration:none;'>Go to Login</a>
    </div>");
}

require_once __DIR__ . '/config/tenant_manager.php';

$step   = (int)($_GET['step'] ?? 1);
$errors = [];
$success = [];

// ── Helpers ───────────────────────────────────────────────────────────
function checkExt(string $ext): string {
    return extension_loaded($ext)
        ? "<span style='color:#16a34a;font-weight:700;'>&#10003; {$ext}</span>"
        : "<span style='color:#dc2626;font-weight:700;'>&#10007; {$ext} — MISSING</span>";
}

function envGet(string $key, $default = ''): string {
    $f = ROOT_PATH . '/config/env.php';
    static $conf = null;
    if (!$conf && file_exists($f)) $conf = require $f;
    return (string)($conf[$key] ?? $default);
}

// ── Step 2: Save credentials ──────────────────────────────────────────
if ($step === 2 && $_SERVER['REQUEST_METHOD'] === 'POST') {
    $cfg = [
        'DB_HOST'          => trim($_POST['db_host'] ?? 'localhost'),
        'DB_USER'          => trim($_POST['db_user'] ?? ''),
        'DB_PASS'          => trim($_POST['db_pass'] ?? ''),
        'DB_NAME'          => trim($_POST['db_name'] ?? ''),
        'DB_PREFIX'        => '',
        'TENANT_DB_HOST'   => trim($_POST['db_host'] ?? 'localhost'),
        'TENANT_POOL_SIZE' => 50,
    ];

    if (!$cfg['DB_USER'] || !$cfg['DB_NAME']) {
        $errors[] = 'Database username and name are required.';
        $step = 2;
    } else {
        // Write env.php
        $out  = "<?php\n/**\n * Auto-generated by RosmonSMS Installer — " . date('Y-m-d H:i:s') . "\n */\nreturn [\n";
        foreach ($cfg as $k => $v) {
            $out .= "    '{$k}' => " . (is_int($v) ? $v : "'" . addslashes($v) . "'") . ",\n";
        }
        $out .= "];\n";
        file_put_contents(__DIR__ . '/config/env.php', $out);

        // Test connection
        try {
            $testPdo = new PDO(
                "mysql:host={$cfg['DB_HOST']};dbname={$cfg['DB_NAME']};charset=utf8mb4",
                $cfg['DB_USER'], $cfg['DB_PASS'],
                [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
            );
            $success[] = "Connected to supervisor database '{$cfg['DB_NAME']}' successfully.";
            header('Location: install.php?step=3');
            exit;
        } catch (PDOException $e) {
            $errors[] = "Cannot connect to '{$cfg['DB_NAME']}': " . $e->getMessage();
            $step = 2;
        }
    }
}

// ── Step 3: Install supervisor schema ─────────────────────────────────
if ($step === 3 && $_SERVER['REQUEST_METHOD'] === 'POST') {
    try {
        // Force reload config by using getSupervisorConnection
        $pdo = TenantManager::getSupervisorConnection();

        // Import supervisor schema
        $schemaFile = __DIR__ . '/database/supervisor_schema_utf8.sql';
        if (!file_exists($schemaFile)) {
            $schemaFile = __DIR__ . '/database/supervisor_schema.sql';
        }
        if (!file_exists($schemaFile)) {
            throw new Exception('Supervisor schema file not found. Ensure database/supervisor_schema_utf8.sql exists.');
        }

        TenantManager::runSqlFile($pdo, $schemaFile);
        $success[] = "Supervisor schema imported successfully.";

        // Create super admin
        $adminEmail = trim($_POST['admin_email'] ?? 'admin@rosmonsms.com');
        $adminPass  = trim($_POST['admin_pass']  ?? 'Admin@12345');
        $adminName  = trim($_POST['admin_name']  ?? 'Super Admin');

        if (strlen($adminPass) < 8) {
            throw new Exception('Admin password must be at least 8 characters.');
        }

        $hashedPass = password_hash($adminPass, PASSWORD_DEFAULT);

        // Ensure users table exists
        try {
            $pdo->exec("CREATE TABLE IF NOT EXISTS `users` (
              `id` int NOT NULL AUTO_INCREMENT,
              `full_name` varchar(200) NOT NULL,
              `email` varchar(200) NOT NULL,
              `username` varchar(200) NOT NULL,
              `password` varchar(255) NOT NULL,
              `role` varchar(50) NOT NULL DEFAULT 'school_admin',
              `tenant_id` int DEFAULT NULL,
              `phone` varchar(50) DEFAULT NULL,
              `is_active` tinyint(1) DEFAULT 1,
              `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
              PRIMARY KEY (`id`),
              UNIQUE KEY `uq_email` (`email`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
        } catch (PDOException $ignored) {}

        // Insert or update super admin
        $existing = $pdo->prepare("SELECT id FROM users WHERE role='super_admin' LIMIT 1");
        $existing->execute();
        if (!$existing->fetch()) {
            $pdo->prepare("INSERT INTO users (full_name,email,username,password,role,tenant_id) VALUES (?,?,?,'','super_admin',NULL)")
                ->execute([$adminName, $adminEmail, $adminEmail]);
            $newId = $pdo->lastInsertId();
            $pdo->prepare("UPDATE users SET password=? WHERE id=?")->execute([$hashedPass, $newId]);
        } else {
            $pdo->prepare("UPDATE users SET full_name=?,email=?,username=?,password=? WHERE role='super_admin'")
                ->execute([$adminName, $adminEmail, $adminEmail, $hashedPass]);
        }
        $success[] = "Super admin account created: {$adminEmail}";

        // Populate pool (50 slots)
        TenantManager::ensurePoolTableExists($pdo);
        $poolResult = TenantManager::populatePool();
        $success[] = "Database pool populated: {$poolResult['added']} slots added, {$poolResult['skipped']} already existed.";

        // Create install lock file
        file_put_contents(__DIR__ . '/.installed', date('Y-m-d H:i:s'));

        header('Location: install.php?step=4&done=1');
        exit;

    } catch (Exception $e) {
        $errors[] = $e->getMessage();
        $step = 3;
    }
}

// ── Derive pool preview ───────────────────────────────────────────────
$poolPreview = [];
if ($step === 3) {
    try {
        for ($i = 1; $i <= 5; $i++) {
            $poolPreview[] = TenantManager::deriveTenantCredentials($i);
        }
    } catch (Throwable $ignored) {}
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>RosmonSMS Installer</title>
<style>
  *{box-sizing:border-box;margin:0;padding:0}
  body{font-family:'Segoe UI',sans-serif;background:#f1f5f9;min-height:100vh;display:flex;align-items:center;justify-content:center;padding:24px}
  .box{background:#fff;border-radius:16px;box-shadow:0 4px 32px rgba(0,0,0,.1);max-width:680px;width:100%;padding:40px}
  .logo{text-align:center;margin-bottom:32px}
  .logo h1{font-size:26px;color:#1e293b;font-weight:800}
  .logo span{color:#2563eb}
  .steps{display:flex;gap:0;margin-bottom:32px;border-bottom:2px solid #e2e8f0;padding-bottom:16px}
  .step{flex:1;text-align:center;font-size:13px;color:#94a3b8;font-weight:600}
  .step.active{color:#2563eb}
  .step.done{color:#16a34a}
  .step-num{display:inline-flex;align-items:center;justify-content:center;width:28px;height:28px;border-radius:50%;background:#e2e8f0;color:#64748b;font-size:12px;font-weight:700;margin-bottom:4px}
  .step.active .step-num{background:#2563eb;color:#fff}
  .step.done .step-num{background:#16a34a;color:#fff}
  h2{font-size:20px;color:#1e293b;margin-bottom:8px}
  p.sub{color:#64748b;font-size:14px;margin-bottom:24px}
  .alert{padding:12px 16px;border-radius:8px;margin-bottom:16px;font-size:14px}
  .alert-error{background:#fef2f2;color:#dc2626;border:1px solid #fecaca}
  .alert-success{background:#f0fdf4;color:#16a34a;border:1px solid #bbf7d0}
  .form-group{margin-bottom:18px}
  label{display:block;font-size:13px;font-weight:600;color:#374151;margin-bottom:6px}
  input{width:100%;padding:10px 14px;border:1.5px solid #d1d5db;border-radius:8px;font-size:14px;outline:none;transition:border .2s}
  input:focus{border-color:#2563eb}
  .btn{display:inline-block;padding:12px 28px;background:#2563eb;color:#fff;border:none;border-radius:8px;font-size:15px;font-weight:600;cursor:pointer;text-decoration:none;width:100%;text-align:center}
  .btn:hover{background:#1d4ed8}
  .btn-green{background:#16a34a}
  .btn-green:hover{background:#15803d}
  .check-row{display:flex;align-items:center;gap:10px;padding:8px 0;border-bottom:1px solid #f1f5f9;font-size:14px}
  .pool-table{width:100%;border-collapse:collapse;font-size:13px;margin-top:12px}
  .pool-table th,.pool-table td{padding:8px 12px;border:1px solid #e2e8f0;text-align:left}
  .pool-table th{background:#f8fafc;font-weight:700;color:#374151}
  code{background:#f1f5f9;padding:2px 6px;border-radius:4px;font-size:13px}
  .done-box{text-align:center;padding:20px 0}
  .done-box .icon{font-size:64px;margin-bottom:16px}
  .done-box h2{font-size:24px;color:#16a34a;margin-bottom:8px}
  .info-box{background:#eff6ff;border:1px solid #bfdbfe;border-radius:8px;padding:16px;font-size:13px;margin-bottom:20px;line-height:1.7}
  .info-box b{color:#1d4ed8}
</style>
</head>
<body>
<div class="box">
  <div class="logo">
    <h1>Rosmon<span>SMS</span></h1>
    <p style="color:#64748b;font-size:13px">School Management System — Installer</p>
  </div>

  <div class="steps">
    <?php
    $stepLabels = ['Requirements','Database Setup','Install & Admin','Complete'];
    foreach ($stepLabels as $idx => $label):
        $num = $idx + 1;
        $cls = $num < $step ? 'done' : ($num === $step ? 'active' : '');
        $numDisplay = $num < $step ? '&#10003;' : $num;
    ?>
    <div class="step <?= $cls ?>">
      <div class="step-num"><?= $numDisplay ?></div><br><?= $label ?>
    </div>
    <?php endforeach; ?>
  </div>

  <?php foreach ($errors as $e): ?>
    <div class="alert alert-error">&#9888; <?= htmlspecialchars($e) ?></div>
  <?php endforeach; ?>
  <?php foreach ($success as $s): ?>
    <div class="alert alert-success">&#10003; <?= htmlspecialchars($s) ?></div>
  <?php endforeach; ?>

  <?php if ($step === 1): ?>
  <h2>System Requirements</h2>
  <p class="sub">Checking that your server meets all requirements before installation.</p>
  <div>
    <div class="check-row"><?= checkExt('pdo') ?> &nbsp;PDO (Database abstraction)</div>
    <div class="check-row"><?= checkExt('pdo_mysql') ?> &nbsp;PDO MySQL driver</div>
    <div class="check-row"><?= checkExt('mbstring') ?> &nbsp;mbstring (Multi-byte strings)</div>
    <div class="check-row"><?= checkExt('json') ?> &nbsp;JSON</div>
    <div class="check-row"><?= checkExt('session') ?> &nbsp;Sessions</div>
    <div class="check-row"><?= checkExt('openssl') ?> &nbsp;OpenSSL (License key generation)</div>
    <div class="check-row">
      <?php $phpOk = version_compare(PHP_VERSION,'7.4','>='); ?>
      <span style="color:<?= $phpOk?'#16a34a':'#dc2626' ?>;font-weight:700;">
        <?= $phpOk?'&#10003;':'&#10007;' ?> PHP <?= PHP_VERSION ?>
      </span> &nbsp;(PHP 7.4+ required)
    </div>
    <div class="check-row">
      <?php $writable = is_writable(__DIR__.'/config'); ?>
      <span style="color:<?= $writable?'#16a34a':'#dc2626' ?>;font-weight:700;">
        <?= $writable?'&#10003;':'&#10007;' ?> config/ directory
      </span> &nbsp;<?= $writable?'Writable':'NOT writable — run chmod 755 config/' ?>
    </div>
    <div class="check-row">
      <?php $storWritable = is_writable(__DIR__.'/storage'); ?>
      <span style="color:<?= $storWritable?'#16a34a':'#dc2626' ?>;font-weight:700;">
        <?= $storWritable?'&#10003;':'&#10007;' ?> storage/ directory
      </span> &nbsp;<?= $storWritable?'Writable':'NOT writable — run chmod 755 storage/' ?>
    </div>
  </div>
  <div class="info-box" style="margin-top:20px;">
    <b>Before continuing, ensure you have:</b><br>
    &#9679; Created the supervisor database in cPanel (e.g. <code>middlehi_IDAHOSA</code>)<br>
    &#9679; Created 50 tenant databases: <code>middlehi_IDAHOSA_1</code> → <code>middlehi_IDAHOSA_50</code><br>
    &#9679; Created matching MySQL users with ALL PRIVILEGES for each database<br>
    &#9679; Each tenant DB username = password = DB name
  </div>
  <a href="install.php?step=2" class="btn" style="margin-top:16px;">Continue to Database Setup &rarr;</a>

  <?php elseif ($step === 2): ?>
  <h2>Database Credentials</h2>
  <p class="sub">Enter your <strong>Supervisor (Hub) Database</strong> credentials. Tenant DB credentials are auto-derived.</p>
  <div class="info-box">
    <b>How it works:</b><br>
    Enter your supervisor DB name (e.g. <code>middlehi_IDAHOSA</code>).<br>
    Tenant databases will automatically be: <code>middlehi_IDAHOSA_1</code>, <code>middlehi_IDAHOSA_2</code> ... <code>middlehi_IDAHOSA_50</code>
  </div>
  <form method="POST" action="install.php?step=2">
    <div class="form-group">
      <label>Database Host</label>
      <input type="text" name="db_host" value="localhost" placeholder="localhost">
    </div>
    <div class="form-group">
      <label>Supervisor Database Name <span style="color:#dc2626">*</span></label>
      <input type="text" name="db_name" value="<?= htmlspecialchars(envGet('DB_NAME','rosmonsms')) ?>"
             placeholder="e.g. middlehi_IDAHOSA" required>
    </div>
    <div class="form-group">
      <label>Database Username <span style="color:#dc2626">*</span></label>
      <input type="text" name="db_user" value="<?= htmlspecialchars(envGet('DB_USER','root')) ?>"
             placeholder="e.g. middlehi_IDAHOSA" required>
    </div>
    <div class="form-group">
      <label>Database Password</label>
      <input type="password" name="db_pass" placeholder="Leave blank if no password">
    </div>
    <button type="submit" class="btn">Test Connection & Save &rarr;</button>
  </form>

  <?php elseif ($step === 3): ?>
  <h2>Install Database & Create Admin</h2>
  <p class="sub">Import the supervisor schema, create your super admin, and register all 50 tenant slots.</p>

  <?php if (!empty($poolPreview)): ?>
  <div class="info-box">
    <b>Pool slots that will be registered:</b>
    <table class="pool-table" style="margin-top:8px;">
      <thead><tr><th>#</th><th>DB Name</th><th>User</th><th>Password</th></tr></thead>
      <tbody>
        <?php foreach ($poolPreview as $p): ?>
        <tr><td><?= $p['pool_index'] ?></td><td><?= $p['db_name'] ?></td><td><?= $p['db_user'] ?></td><td><?= $p['db_pass'] ?></td></tr>
        <?php endforeach; ?>
        <tr><td colspan="4" style="text-align:center;color:#64748b;">... up to slot 50</td></tr>
      </tbody>
    </table>
  </div>
  <?php endif; ?>

  <form method="POST" action="install.php?step=3">
    <div class="form-group">
      <label>Super Admin Full Name</label>
      <input type="text" name="admin_name" value="Super Admin" placeholder="e.g. John Doe">
    </div>
    <div class="form-group">
      <label>Super Admin Email <span style="color:#dc2626">*</span></label>
      <input type="email" name="admin_email" value="admin@rosmonsms.com" required>
    </div>
    <div class="form-group">
      <label>Super Admin Password <span style="color:#dc2626">*</span> (min 8 chars)</label>
      <input type="password" name="admin_pass" placeholder="Strong password" required minlength="8">
    </div>
    <button type="submit" class="btn btn-green">&#9889; Run Installation</button>
  </form>

  <?php elseif ($step === 4): ?>
  <div class="done-box">
    <div class="icon">&#127881;</div>
    <h2>RosmonSMS Installed Successfully!</h2>
    <p style="color:#64748b;margin-bottom:24px;font-size:15px;">Your school management system is ready for use.</p>
    <div class="info-box" style="text-align:left;margin-bottom:24px;">
      <b>Next steps:</b><br>
      &#9679; <strong>DELETE</strong> <code>install.php</code> from your server immediately for security.<br>
      &#9679; Create all 50 tenant databases in cPanel if you haven't already.<br>
      &#9679; Log in as Super Admin to start approving schools.<br>
      &#9679; Each approved school gets their private DB auto-provisioned.
    </div>
    <a href="/" class="btn" style="width:auto;">Go to Login &rarr;</a>
  </div>
  <?php endif; ?>

</div>
</body>
</html>
